import 'package:max_country_picker/model/country_model.dart';

class MaxCountryList {
  static List<MaxCountry> get list => _list;
  static final List<MaxCountry> _list = [
    MaxCountry(
        name: "Afghanistan",
        dialCode: "+93",
        code: "AF",
        flagEmoji: "🇦🇫",
        flagIconCircle: "assets/circle/AF.svg",
        flagIconSquare: "assets/square/AF.svg"),
    MaxCountry(
        name: "Aland Islands",
        dialCode: "+358",
        code: "AX",
        flagEmoji: "🇦🇽",
        flagIconCircle: "assets/circle/AX.svg",
        flagIconSquare: "assets/square/AX.svg"),
    MaxCountry(
        name: "Albania",
        dialCode: "+355",
        code: "AL",
        flagEmoji: "🇦🇱",
        flagIconCircle: "assets/circle/AL.svg",
        flagIconSquare: "assets/square/AL.svg"),
    MaxCountry(
        name: "Algeria",
        dialCode: "+213",
        code: "DZ",
        flagEmoji: "🇩🇿",
        flagIconCircle: "assets/circle/DZ.svg",
        flagIconSquare: "assets/square/DZ.svg"),
    MaxCountry(
        name: "American Samoa",
        dialCode: "+1684",
        code: "AS",
        flagEmoji: "🇦🇸",
        flagIconCircle: "assets/circle/AS.svg",
        flagIconSquare: "assets/square/AS.svg"),
    MaxCountry(
        name: "Andorra",
        dialCode: "+376",
        code: "AD",
        flagEmoji: "🇦🇩",
        flagIconCircle: "assets/circle/AD.svg",
        flagIconSquare: "assets/square/AD.svg"),
    MaxCountry(
        name: "Angola",
        dialCode: "+244",
        code: "AO",
        flagEmoji: "🇦🇴",
        flagIconCircle: "assets/circle/AO.svg",
        flagIconSquare: "assets/square/AO.svg"),
    MaxCountry(
        name: "Anguilla",
        dialCode: "+1264",
        code: "AI",
        flagEmoji: "🇦🇮",
        flagIconCircle: "assets/circle/AI.svg",
        flagIconSquare: "assets/square/AI.svg"),
    MaxCountry(
        name: "Antarctica",
        dialCode: "+672",
        code: "AQ",
        flagEmoji: "🇦🇶",
        flagIconCircle: "assets/circle/AQ.svg",
        flagIconSquare: "assets/square/AQ.svg"),
    MaxCountry(
        name: "Antigua and Barbuda",
        dialCode: "+1268",
        code: "AG",
        flagEmoji: "🇦🇬",
        flagIconCircle: "assets/circle/AG.svg",
        flagIconSquare: "assets/square/AG.svg"),
    MaxCountry(
        name: "Argentina",
        dialCode: "+54",
        code: "AR",
        flagEmoji: "🇦🇷",
        flagIconCircle: "assets/circle/AR.svg",
        flagIconSquare: "assets/square/AR.svg"),
    MaxCountry(
        name: "Armenia",
        dialCode: "+374",
        code: "AM",
        flagEmoji: "🇦🇲",
        flagIconCircle: "assets/circle/AM.svg",
        flagIconSquare: "assets/square/AM.svg"),
    MaxCountry(
        name: "Aruba",
        dialCode: "+297",
        code: "AW",
        flagEmoji: "🇦🇼",
        flagIconCircle: "assets/circle/AW.svg",
        flagIconSquare: "assets/square/AW.svg"),
    MaxCountry(
        name: "Australia",
        dialCode: "+61",
        code: "AU",
        flagEmoji: "🇦🇺",
        flagIconCircle: "assets/circle/AU.svg",
        flagIconSquare: "assets/square/AU.svg"),
    MaxCountry(
        name: "Austria",
        dialCode: "+43",
        code: "AT",
        flagEmoji: "🇦🇹",
        flagIconCircle: "assets/circle/AT.svg",
        flagIconSquare: "assets/square/AT.svg"),
    MaxCountry(
        name: "Azerbaijan",
        dialCode: "+994",
        code: "AZ",
        flagEmoji: "🇦🇿",
        flagIconCircle: "assets/circle/AZ.svg",
        flagIconSquare: "assets/square/AZ.svg"),
    MaxCountry(
        name: "Bahamas",
        dialCode: "+1242",
        code: "BS",
        flagEmoji: "🇧🇸",
        flagIconCircle: "assets/circle/BS.svg",
        flagIconSquare: "assets/square/BS.svg"),
    MaxCountry(
        name: "Bahrain",
        dialCode: "+973",
        code: "BH",
        flagEmoji: "🇧🇭",
        flagIconCircle: "assets/circle/BH.svg",
        flagIconSquare: "assets/square/BH.svg"),
    MaxCountry(
        name: "Bangladesh",
        dialCode: "+880",
        code: "BD",
        flagEmoji: "🇧🇩",
        flagIconCircle: "assets/circle/BD.svg",
        flagIconSquare: "assets/square/BD.svg"),
    MaxCountry(
        name: "Barbados",
        dialCode: "+1246",
        code: "BB",
        flagEmoji: "🇧🇧",
        flagIconCircle: "assets/circle/BB.svg",
        flagIconSquare: "assets/square/BB.svg"),
    MaxCountry(
        name: "Belarus",
        dialCode: "+375",
        code: "BY",
        flagEmoji: "🇧🇾",
        flagIconCircle: "assets/circle/BY.svg",
        flagIconSquare: "assets/square/BY.svg"),
    MaxCountry(
        name: "Belgium",
        dialCode: "+32",
        code: "BE",
        flagEmoji: "🇧🇪",
        flagIconCircle: "assets/circle/BE.svg",
        flagIconSquare: "assets/square/BE.svg"),
    MaxCountry(
        name: "Belize",
        dialCode: "+501",
        code: "BZ",
        flagEmoji: "🇧🇿",
        flagIconCircle: "assets/circle/BZ.svg",
        flagIconSquare: "assets/square/BZ.svg"),
    MaxCountry(
        name: "Benin",
        dialCode: "+229",
        code: "BJ",
        flagEmoji: "🇧🇯",
        flagIconCircle: "assets/circle/BJ.svg",
        flagIconSquare: "assets/square/BJ.svg"),
    MaxCountry(
        name: "Bermuda",
        dialCode: "+1441",
        code: "BM",
        flagEmoji: "🇧🇲",
        flagIconCircle: "assets/circle/BM.svg",
        flagIconSquare: "assets/square/BM.svg"),
    MaxCountry(
        name: "Bhutan",
        dialCode: "+975",
        code: "BT",
        flagEmoji: "🇧🇹",
        flagIconCircle: "assets/circle/BT.svg",
        flagIconSquare: "assets/square/BT.svg"),
    MaxCountry(
        name: "Bolivia",
        dialCode: "+591",
        code: "BO",
        flagEmoji: "🇧🇴",
        flagIconCircle: "assets/circle/BO.svg",
        flagIconSquare: "assets/square/BO.svg"),
    MaxCountry(
        name: "Bosnia and Herzegovina",
        dialCode: "+387",
        code: "BA",
        flagEmoji: "🇧🇦",
        flagIconCircle: "assets/circle/BA.svg",
        flagIconSquare: "assets/square/BA.svg"),
    MaxCountry(
        name: "Botswana",
        dialCode: "+267",
        code: "BW",
        flagEmoji: "🇧🇼",
        flagIconCircle: "assets/circle/BW.svg",
        flagIconSquare: "assets/square/BW.svg"),
    MaxCountry(
        name: "Brazil",
        dialCode: "+55",
        code: "BR",
        flagEmoji: "🇧🇷",
        flagIconCircle: "assets/circle/BR.svg",
        flagIconSquare: "assets/square/BR.svg"),
    MaxCountry(
        name: "British Indian Ocean Territory",
        dialCode: "+246",
        code: "IO",
        flagEmoji: "🇮🇴",
        flagIconCircle: "assets/circle/IO.svg",
        flagIconSquare: "assets/square/IO.svg"),
    MaxCountry(
        name: "Brunei Darussalam",
        dialCode: "+673",
        code: "BN",
        flagEmoji: "🇧🇳",
        flagIconCircle: "assets/circle/BN.svg",
        flagIconSquare: "assets/square/BN.svg"),
    MaxCountry(
        name: "Bulgaria",
        dialCode: "+359",
        code: "BG",
        flagEmoji: "🇧🇬",
        flagIconCircle: "assets/circle/BG.svg",
        flagIconSquare: "assets/square/BG.svg"),
    MaxCountry(
        name: "Burkina Faso",
        dialCode: "+226",
        code: "BF",
        flagEmoji: "🇧🇫",
        flagIconCircle: "assets/circle/BF.svg",
        flagIconSquare: "assets/square/BF.svg"),
    MaxCountry(
        name: "Burundi",
        dialCode: "+257",
        code: "BI",
        flagEmoji: "🇧🇮",
        flagIconCircle: "assets/circle/BI.svg",
        flagIconSquare: "assets/square/BI.svg"),
    MaxCountry(
        name: "Cambodia",
        dialCode: "+855",
        code: "KH",
        flagEmoji: "🇰🇭",
        flagIconCircle: "assets/circle/KH.svg",
        flagIconSquare: "assets/square/KH.svg"),
    MaxCountry(
        name: "Cameroon",
        dialCode: "+237",
        code: "CM",
        flagEmoji: "🇨🇲",
        flagIconCircle: "assets/circle/CM.svg",
        flagIconSquare: "assets/square/CM.svg"),
    MaxCountry(
        name: "Canada",
        dialCode: "+1",
        code: "CA",
        flagEmoji: "🇨🇦",
        flagIconCircle: "assets/circle/CA.svg",
        flagIconSquare: "assets/square/CA.svg"),
    MaxCountry(
        name: "Cape Verde",
        dialCode: "+238",
        code: "CV",
        flagEmoji: "🇨🇻",
        flagIconCircle: "assets/circle/CV.svg",
        flagIconSquare: "assets/square/CV.svg"),
    MaxCountry(
        name: "Cayman Islands",
        dialCode: "+ 345",
        code: "KY",
        flagEmoji: "🇰🇾",
        flagIconCircle: "assets/circle/KY.svg",
        flagIconSquare: "assets/square/KY.svg"),
    MaxCountry(
        name: "Central African Republic",
        dialCode: "+236",
        code: "CF",
        flagEmoji: "🇨🇫",
        flagIconCircle: "assets/circle/CF.svg",
        flagIconSquare: "assets/square/CF.svg"),
    MaxCountry(
        name: "Chad",
        dialCode: "+235",
        code: "TD",
        flagEmoji: "🇹🇩",
        flagIconCircle: "assets/circle/TD.svg",
        flagIconSquare: "assets/square/TD.svg"),
    MaxCountry(
        name: "Chile",
        dialCode: "+56",
        code: "CL",
        flagEmoji: "🇨🇱",
        flagIconCircle: "assets/circle/CL.svg",
        flagIconSquare: "assets/square/CL.svg"),
    MaxCountry(
        name: "China",
        dialCode: "+86",
        code: "CN",
        flagEmoji: "🇨🇳",
        flagIconCircle: "assets/circle/CN.svg",
        flagIconSquare: "assets/square/CN.svg"),
    MaxCountry(
        name: "Christmas Island",
        dialCode: "+61",
        code: "CX",
        flagEmoji: "🇨🇽",
        flagIconCircle: "assets/circle/CX.svg",
        flagIconSquare: "assets/square/CX.svg"),
    MaxCountry(
        name: "Cocos (Keeling) Islands",
        dialCode: "+61",
        code: "CC",
        flagEmoji: "🇨🇨",
        flagIconCircle: "assets/circle/CC.svg",
        flagIconSquare: "assets/square/CC.svg"),
    MaxCountry(
        name: "Colombia",
        dialCode: "+57",
        code: "CO",
        flagEmoji: "🇨🇴",
        flagIconCircle: "assets/circle/CO.svg",
        flagIconSquare: "assets/square/CO.svg"),
    MaxCountry(
        name: "Comoros",
        dialCode: "+269",
        code: "KM",
        flagEmoji: "🇰🇲",
        flagIconCircle: "assets/circle/KM.svg",
        flagIconSquare: "assets/square/KM.svg"),
    MaxCountry(
        name: "Congo",
        dialCode: "+242",
        code: "CG",
        flagEmoji: "🇨🇬",
        flagIconCircle: "assets/circle/CG.svg",
        flagIconSquare: "assets/square/CG.svg"),
    MaxCountry(
        name: "Congo, The Democratic Republic of the Congo",
        dialCode: "+243",
        code: "CD",
        flagEmoji: "🇨🇩",
        flagIconCircle: "assets/circle/CD.svg",
        flagIconSquare: "assets/square/CD.svg"),
    MaxCountry(
        name: "Cook Islands",
        dialCode: "+682",
        code: "CK",
        flagEmoji: "🇨🇰",
        flagIconCircle: "assets/circle/CK.svg",
        flagIconSquare: "assets/square/CK.svg"),
    MaxCountry(
        name: "Costa Rica",
        dialCode: "+506",
        code: "CR",
        flagEmoji: "🇨🇷",
        flagIconCircle: "assets/circle/CR.svg",
        flagIconSquare: "assets/square/CR.svg"),
    MaxCountry(
        name: "Cote d'Ivoire",
        dialCode: "+225",
        code: "CI",
        flagEmoji: "🇨🇮",
        flagIconCircle: "assets/circle/CI.svg",
        flagIconSquare: "assets/square/CI.svg"),
    MaxCountry(
        name: "Croatia",
        dialCode: "+385",
        code: "HR",
        flagEmoji: "🇭🇷",
        flagIconCircle: "assets/circle/HR.svg",
        flagIconSquare: "assets/square/HR.svg"),
    MaxCountry(
        name: "Cuba",
        dialCode: "+53",
        code: "CU",
        flagEmoji: "🇨🇺",
        flagIconCircle: "assets/circle/CU.svg",
        flagIconSquare: "assets/square/CU.svg"),
    MaxCountry(
        name: "Cyprus",
        dialCode: "+357",
        code: "CY",
        flagEmoji: "🇨🇾",
        flagIconCircle: "assets/circle/CY.svg",
        flagIconSquare: "assets/square/CY.svg"),
    MaxCountry(
        name: "Czech Republic",
        dialCode: "+420",
        code: "CZ",
        flagEmoji: "🇨🇿",
        flagIconCircle: "assets/circle/CZ.svg",
        flagIconSquare: "assets/square/CZ.svg"),
    MaxCountry(
        name: "Denmark",
        dialCode: "+45",
        code: "DK",
        flagEmoji: "🇩🇰",
        flagIconCircle: "assets/circle/DK.svg",
        flagIconSquare: "assets/square/DK.svg"),
    MaxCountry(
        name: "Djibouti",
        dialCode: "+253",
        code: "DJ",
        flagEmoji: "🇩🇯",
        flagIconCircle: "assets/circle/DJ.svg",
        flagIconSquare: "assets/square/DJ.svg"),
    MaxCountry(
        name: "Dominica",
        dialCode: "+1767",
        code: "DM",
        flagEmoji: "🇩🇲",
        flagIconCircle: "assets/circle/DM.svg",
        flagIconSquare: "assets/square/DM.svg"),
    MaxCountry(
        name: "Dominican Republic",
        dialCode: "+1849",
        code: "DO",
        flagEmoji: "🇩🇴",
        flagIconCircle: "assets/circle/DO.svg",
        flagIconSquare: "assets/square/DO.svg"),
    MaxCountry(
        name: "Ecuador",
        dialCode: "+593",
        code: "EC",
        flagEmoji: "🇪🇨",
        flagIconCircle: "assets/circle/EC.svg",
        flagIconSquare: "assets/square/EC.svg"),
    MaxCountry(
        name: "Egypt",
        dialCode: "+20",
        code: "EG",
        flagEmoji: "🇪🇬",
        flagIconCircle: "assets/circle/EG.svg",
        flagIconSquare: "assets/square/EG.svg"),
    MaxCountry(
        name: "El Salvador",
        dialCode: "+503",
        code: "SV",
        flagEmoji: "🇸🇻",
        flagIconCircle: "assets/circle/SV.svg",
        flagIconSquare: "assets/square/SV.svg"),
    MaxCountry(
        name: "Equatorial Guinea",
        dialCode: "+240",
        code: "GQ",
        flagEmoji: "🇬🇶",
        flagIconCircle: "assets/circle/GQ.svg",
        flagIconSquare: "assets/square/GQ.svg"),
    MaxCountry(
        name: "Eritrea",
        dialCode: "+291",
        code: "ER",
        flagEmoji: "🇪🇷",
        flagIconCircle: "assets/circle/ER.svg",
        flagIconSquare: "assets/square/ER.svg"),
    MaxCountry(
        name: "Estonia",
        dialCode: "+372",
        code: "EE",
        flagEmoji: "🇪🇪",
        flagIconCircle: "assets/circle/EE.svg",
        flagIconSquare: "assets/square/EE.svg"),
    MaxCountry(
        name: "Ethiopia",
        dialCode: "+251",
        code: "ET",
        flagEmoji: "🇪🇹",
        flagIconCircle: "assets/circle/ET.svg",
        flagIconSquare: "assets/square/ET.svg"),
    MaxCountry(
        name: "Falkland Islands (Malvinas)",
        dialCode: "+500",
        code: "FK",
        flagEmoji: "🇫🇰",
        flagIconCircle: "assets/circle/FK.svg",
        flagIconSquare: "assets/square/FK.svg"),
    MaxCountry(
        name: "Faroe Islands",
        dialCode: "+298",
        code: "FO",
        flagEmoji: "🇫🇴",
        flagIconCircle: "assets/circle/FO.svg",
        flagIconSquare: "assets/square/FO.svg"),
    MaxCountry(
        name: "Fiji",
        dialCode: "+679",
        code: "FJ",
        flagEmoji: "🇫🇯",
        flagIconCircle: "assets/circle/FJ.svg",
        flagIconSquare: "assets/square/FJ.svg"),
    MaxCountry(
        name: "Finland",
        dialCode: "+358",
        code: "FI",
        flagEmoji: "🇫🇮",
        flagIconCircle: "assets/circle/FI.svg",
        flagIconSquare: "assets/square/FI.svg"),
    MaxCountry(
        name: "France",
        dialCode: "+33",
        code: "FR",
        flagEmoji: "🇫🇷",
        flagIconCircle: "assets/circle/FR.svg",
        flagIconSquare: "assets/square/FR.svg"),
    MaxCountry(
        name: "French Guiana",
        dialCode: "+594",
        code: "GF",
        flagEmoji: "🇬🇫",
        flagIconCircle: "assets/circle/GF.svg",
        flagIconSquare: "assets/square/GF.svg"),
    MaxCountry(
        name: "French Polynesia",
        dialCode: "+689",
        code: "PF",
        flagEmoji: "🇵🇫",
        flagIconCircle: "assets/circle/PF.svg",
        flagIconSquare: "assets/square/PF.svg"),
    MaxCountry(
        name: "Gabon",
        dialCode: "+241",
        code: "GA",
        flagEmoji: "🇬🇦",
        flagIconCircle: "assets/circle/GA.svg",
        flagIconSquare: "assets/square/GA.svg"),
    MaxCountry(
        name: "Gambia",
        dialCode: "+220",
        code: "GM",
        flagEmoji: "🇬🇲",
        flagIconCircle: "assets/circle/GM.svg",
        flagIconSquare: "assets/square/GM.svg"),
    MaxCountry(
        name: "Georgia",
        dialCode: "+995",
        code: "GE",
        flagEmoji: "🇬🇪",
        flagIconCircle: "assets/circle/GE.svg",
        flagIconSquare: "assets/square/GE.svg"),
    MaxCountry(
        name: "Germany",
        dialCode: "+49",
        code: "DE",
        flagEmoji: "🇩🇪",
        flagIconCircle: "assets/circle/DE.svg",
        flagIconSquare: "assets/square/DE.svg"),
    MaxCountry(
        name: "Ghana",
        dialCode: "+233",
        code: "GH",
        flagEmoji: "🇬🇭",
        flagIconCircle: "assets/circle/GH.svg",
        flagIconSquare: "assets/square/GH.svg"),
    MaxCountry(
        name: "Gibraltar",
        dialCode: "+350",
        code: "GI",
        flagEmoji: "🇬🇮",
        flagIconCircle: "assets/circle/GI.svg",
        flagIconSquare: "assets/square/GI.svg"),
    MaxCountry(
        name: "Greece",
        dialCode: "+30",
        code: "GR",
        flagEmoji: "🇬🇷",
        flagIconCircle: "assets/circle/GR.svg",
        flagIconSquare: "assets/square/GR.svg"),
    MaxCountry(
        name: "Greenland",
        dialCode: "+299",
        code: "GL",
        flagEmoji: "🇬🇱",
        flagIconCircle: "assets/circle/GL.svg",
        flagIconSquare: "assets/square/GL.svg"),
    MaxCountry(
        name: "Grenada",
        dialCode: "+1473",
        code: "GD",
        flagEmoji: "🇬🇩",
        flagIconCircle: "assets/circle/GD.svg",
        flagIconSquare: "assets/square/GD.svg"),
    MaxCountry(
        name: "Guadeloupe",
        dialCode: "+590",
        code: "GP",
        flagEmoji: "🇬🇵",
        flagIconCircle: "assets/circle/GP.svg",
        flagIconSquare: "assets/square/GP.svg"),
    MaxCountry(
        name: "Guam",
        dialCode: "+1671",
        code: "GU",
        flagEmoji: "🇬🇺",
        flagIconCircle: "assets/circle/GU.svg",
        flagIconSquare: "assets/square/GU.svg"),
    MaxCountry(
        name: "Guatemala",
        dialCode: "+502",
        code: "GT",
        flagEmoji: "🇬🇹",
        flagIconCircle: "assets/circle/GT.svg",
        flagIconSquare: "assets/square/GT.svg"),
    MaxCountry(
        name: "Guernsey",
        dialCode: "+44",
        code: "GG",
        flagEmoji: "🇬🇬",
        flagIconCircle: "assets/circle/GG.svg",
        flagIconSquare: "assets/square/GG.svg"),
    MaxCountry(
        name: "Guinea",
        dialCode: "+224",
        code: "GN",
        flagEmoji: "🇬🇳",
        flagIconCircle: "assets/circle/GN.svg",
        flagIconSquare: "assets/square/GN.svg"),
    MaxCountry(
        name: "Guinea Bissau",
        dialCode: "+245",
        code: "GW",
        flagEmoji: "🇬🇼",
        flagIconCircle: "assets/circle/GW.svg",
        flagIconSquare: "assets/square/GW.svg"),
    MaxCountry(
        name: "Guyana",
        dialCode: "+595",
        code: "GY",
        flagEmoji: "🇬🇾",
        flagIconCircle: "assets/circle/GY.svg",
        flagIconSquare: "assets/square/GY.svg"),
    MaxCountry(
        name: "Haiti",
        dialCode: "+509",
        code: "HT",
        flagEmoji: "🇭🇹",
        flagIconCircle: "assets/circle/HT.svg",
        flagIconSquare: "assets/square/HT.svg"),
    MaxCountry(
        name: "Holy See (Vatican City State)",
        dialCode: "+379",
        code: "VA",
        flagEmoji: "🇻🇦",
        flagIconCircle: "assets/circle/VA.svg",
        flagIconSquare: "assets/square/VA.svg"),
    MaxCountry(
        name: "Honduras",
        dialCode: "+504",
        code: "HN",
        flagEmoji: "🇭🇳",
        flagIconCircle: "assets/circle/HN.svg",
        flagIconSquare: "assets/square/HN.svg"),
    MaxCountry(
        name: "Hong Kong",
        dialCode: "+852",
        code: "HK",
        flagEmoji: "🇭🇰",
        flagIconCircle: "assets/circle/HK.svg",
        flagIconSquare: "assets/square/HK.svg"),
    MaxCountry(
        name: "Hungary",
        dialCode: "+36",
        code: "HU",
        flagEmoji: "🇭🇺",
        flagIconCircle: "assets/circle/HU.svg",
        flagIconSquare: "assets/square/HU.svg"),
    MaxCountry(
        name: "Iceland",
        dialCode: "+354",
        code: "IS",
        flagEmoji: "🇮🇸",
        flagIconCircle: "assets/circle/IS.svg",
        flagIconSquare: "assets/square/IS.svg"),
    MaxCountry(
        name: "India",
        dialCode: "+91",
        code: "IN",
        flagEmoji: "🇮🇳",
        flagIconCircle: "assets/circle/IN.svg",
        flagIconSquare: "assets/square/IN.svg"),
    MaxCountry(
        name: "Indonesia",
        dialCode: "+62",
        code: "ID",
        flagEmoji: "🇮🇩",
        flagIconCircle: "assets/circle/ID.svg",
        flagIconSquare: "assets/square/ID.svg"),
    MaxCountry(
        name: "Iran, Islamic Republic of Persian Gulf",
        dialCode: "+98",
        code: "IR",
        flagEmoji: "🇮🇷",
        flagIconCircle: "assets/circle/IR.svg",
        flagIconSquare: "assets/square/IR.svg"),
    MaxCountry(
        name: "Iraq",
        dialCode: "+964",
        code: "IQ",
        flagEmoji: "🇮🇶",
        flagIconCircle: "assets/circle/IQ.svg",
        flagIconSquare: "assets/square/IQ.svg"),
    MaxCountry(
        name: "Ireland",
        dialCode: "+353",
        code: "IE",
        flagEmoji: "🇮🇪",
        flagIconCircle: "assets/circle/IE.svg",
        flagIconSquare: "assets/square/IE.svg"),
    MaxCountry(
        name: "Isle of Man",
        dialCode: "+44",
        code: "IM",
        flagEmoji: "🇮🇲",
        flagIconCircle: "assets/circle/IM.svg",
        flagIconSquare: "assets/square/IM.svg"),
    MaxCountry(
        name: "Israel",
        dialCode: "+972",
        code: "IL",
        flagEmoji: "🇮🇱",
        flagIconCircle: "assets/circle/IL.svg",
        flagIconSquare: "assets/square/IL.svg"),
    MaxCountry(
        name: "Italy",
        dialCode: "+39",
        code: "IT",
        flagEmoji: "🇮🇹",
        flagIconCircle: "assets/circle/IT.svg",
        flagIconSquare: "assets/square/IT.svg"),
    MaxCountry(
        name: "Jamaica",
        dialCode: "+1876",
        code: "JM",
        flagEmoji: "🇯🇲",
        flagIconCircle: "assets/circle/JM.svg",
        flagIconSquare: "assets/square/JM.svg"),
    MaxCountry(
        name: "Japan",
        dialCode: "+81",
        code: "JP",
        flagEmoji: "🇯🇵",
        flagIconCircle: "assets/circle/JP.svg",
        flagIconSquare: "assets/square/JP.svg"),
    MaxCountry(
        name: "Jersey",
        dialCode: "+44",
        code: "JE",
        flagEmoji: "🇯🇪",
        flagIconCircle: "assets/circle/JE.svg",
        flagIconSquare: "assets/square/JE.svg"),
    MaxCountry(
        name: "Jordan",
        dialCode: "+962",
        code: "JO",
        flagEmoji: "🇯🇴",
        flagIconCircle: "assets/circle/JO.svg",
        flagIconSquare: "assets/square/JO.svg"),
    MaxCountry(
        name: "Kazakhstan",
        dialCode: "+77",
        code: "KZ",
        flagEmoji: "🇰🇿",
        flagIconCircle: "assets/circle/KZ.svg",
        flagIconSquare: "assets/square/KZ.svg"),
    MaxCountry(
        name: "Kenya",
        dialCode: "+254",
        code: "KE",
        flagEmoji: "🇰🇪",
        flagIconCircle: "assets/circle/KE.svg",
        flagIconSquare: "assets/square/KE.svg"),
    MaxCountry(
        name: "Kiribati",
        dialCode: "+686",
        code: "KI",
        flagEmoji: "🇰🇮",
        flagIconCircle: "assets/circle/KI.svg",
        flagIconSquare: "assets/square/KI.svg"),
    MaxCountry(
        name: "Korea, Democratic People's Republic of Korea",
        dialCode: "+850",
        code: "KP",
        flagEmoji: "🇰🇵",
        flagIconCircle: "assets/circle/KP.svg",
        flagIconSquare: "assets/square/KP.svg"),
    MaxCountry(
        name: "Korea, Republic of South Korea",
        dialCode: "+82",
        code: "KR",
        flagEmoji: "🇰🇷",
        flagIconCircle: "assets/circle/KR.svg",
        flagIconSquare: "assets/square/KR.svg"),
    MaxCountry(
        name: "Kuwait",
        dialCode: "+965",
        code: "KW",
        flagEmoji: "🇰🇼",
        flagIconCircle: "assets/circle/KW.svg",
        flagIconSquare: "assets/square/KW.svg"),
    MaxCountry(
        name: "Kyrgyzstan",
        dialCode: "+996",
        code: "KG",
        flagEmoji: "🇰🇬",
        flagIconCircle: "assets/circle/KG.svg",
        flagIconSquare: "assets/square/KG.svg"),
    MaxCountry(
        name: "Laos",
        dialCode: "+856",
        code: "LA",
        flagEmoji: "🇱🇦",
        flagIconCircle: "assets/circle/LA.svg",
        flagIconSquare: "assets/square/LA.svg"),
    MaxCountry(
        name: "Latvia",
        dialCode: "+371",
        code: "LV",
        flagEmoji: "🇱🇻",
        flagIconCircle: "assets/circle/LV.svg",
        flagIconSquare: "assets/square/LV.svg"),
    MaxCountry(
        name: "Lebanon",
        dialCode: "+961",
        code: "LB",
        flagEmoji: "🇱🇧",
        flagIconCircle: "assets/circle/LB.svg",
        flagIconSquare: "assets/square/LB.svg"),
    MaxCountry(
        name: "Lesotho",
        dialCode: "+266",
        code: "LS",
        flagEmoji: "🇱🇸",
        flagIconCircle: "assets/circle/LS.svg",
        flagIconSquare: "assets/square/LS.svg"),
    MaxCountry(
        name: "Liberia",
        dialCode: "+231",
        code: "LR",
        flagEmoji: "🇱🇷",
        flagIconCircle: "assets/circle/LR.svg",
        flagIconSquare: "assets/square/LR.svg"),
    MaxCountry(
        name: "Libyan Arab Jamahiriya",
        dialCode: "+218",
        code: "LY",
        flagEmoji: "🇱🇾",
        flagIconCircle: "assets/circle/LY.svg",
        flagIconSquare: "assets/square/LY.svg"),
    MaxCountry(
        name: "Liechtenstein",
        dialCode: "+423",
        code: "LI",
        flagEmoji: "🇱🇮",
        flagIconCircle: "assets/circle/LI.svg",
        flagIconSquare: "assets/square/LI.svg"),
    MaxCountry(
        name: "Lithuania",
        dialCode: "+370",
        code: "LT",
        flagEmoji: "🇱🇹",
        flagIconCircle: "assets/circle/LT.svg",
        flagIconSquare: "assets/square/LT.svg"),
    MaxCountry(
        name: "Luxembourg",
        dialCode: "+352",
        code: "LU",
        flagEmoji: "🇱🇺",
        flagIconCircle: "assets/circle/LU.svg",
        flagIconSquare: "assets/square/LU.svg"),
    MaxCountry(
        name: "Macao",
        dialCode: "+853",
        code: "MO",
        flagEmoji: "🇲🇴",
        flagIconCircle: "assets/circle/MO.svg",
        flagIconSquare: "assets/square/MO.svg"),
    MaxCountry(
        name: "Macedonia",
        dialCode: "+389",
        code: "MK",
        flagEmoji: "🇲🇰",
        flagIconCircle: "assets/circle/MK.svg",
        flagIconSquare: "assets/square/MK.svg"),
    MaxCountry(
        name: "Madagascar",
        dialCode: "+261",
        code: "MG",
        flagEmoji: "🇲🇬",
        flagIconCircle: "assets/circle/MG.svg",
        flagIconSquare: "assets/square/MG.svg"),
    MaxCountry(
        name: "Malawi",
        dialCode: "+265",
        code: "MW",
        flagEmoji: "🇲🇼",
        flagIconCircle: "assets/circle/MW.svg",
        flagIconSquare: "assets/square/MW.svg"),
    MaxCountry(
        name: "Malaysia",
        dialCode: "+60",
        code: "MY",
        flagEmoji: "🇲🇾",
        flagIconCircle: "assets/circle/MY.svg",
        flagIconSquare: "assets/square/MY.svg"),
    MaxCountry(
        name: "Maldives",
        dialCode: "+960",
        code: "MV",
        flagEmoji: "🇲🇻",
        flagIconCircle: "assets/circle/MV.svg",
        flagIconSquare: "assets/square/MV.svg"),
    MaxCountry(
        name: "Mali",
        dialCode: "+223",
        code: "ML",
        flagEmoji: "🇲🇱",
        flagIconCircle: "assets/circle/ML.svg",
        flagIconSquare: "assets/square/ML.svg"),
    MaxCountry(
        name: "Malta",
        dialCode: "+356",
        code: "MT",
        flagEmoji: "🇲🇹",
        flagIconCircle: "assets/circle/MT.svg",
        flagIconSquare: "assets/square/MT.svg"),
    MaxCountry(
        name: "Marshall Islands",
        dialCode: "+692",
        code: "MH",
        flagEmoji: "🇲🇭",
        flagIconCircle: "assets/circle/MH.svg",
        flagIconSquare: "assets/square/MH.svg"),
    MaxCountry(
        name: "Martinique",
        dialCode: "+596",
        code: "MQ",
        flagEmoji: "🇲🇶",
        flagIconCircle: "assets/circle/MQ.svg",
        flagIconSquare: "assets/square/MQ.svg"),
    MaxCountry(
        name: "Mauritania",
        dialCode: "+222",
        code: "MR",
        flagEmoji: "🇲🇷",
        flagIconCircle: "assets/circle/MR.svg",
        flagIconSquare: "assets/square/MR.svg"),
    MaxCountry(
        name: "Mauritius",
        dialCode: "+230",
        code: "MU",
        flagEmoji: "🇲🇺",
        flagIconCircle: "assets/circle/MU.svg",
        flagIconSquare: "assets/square/MU.svg"),
    MaxCountry(
        name: "Mayotte",
        dialCode: "+262",
        code: "YT",
        flagEmoji: "🇾🇹",
        flagIconCircle: "assets/circle/YT.svg",
        flagIconSquare: "assets/square/YT.svg"),
    MaxCountry(
        name: "Mexico",
        dialCode: "+52",
        code: "MX",
        flagEmoji: "🇲🇽",
        flagIconCircle: "assets/circle/MX.svg",
        flagIconSquare: "assets/square/MX.svg"),
    MaxCountry(
        name: "Micronesia, Federated States of Micronesia",
        dialCode: "+691",
        code: "FM",
        flagEmoji: "🇫🇲",
        flagIconCircle: "assets/circle/FM.svg",
        flagIconSquare: "assets/square/FM.svg"),
    MaxCountry(
        name: "Moldova",
        dialCode: "+373",
        code: "MD",
        flagEmoji: "🇲🇩",
        flagIconCircle: "assets/circle/MD.svg",
        flagIconSquare: "assets/square/MD.svg"),
    MaxCountry(
        name: "Monaco",
        dialCode: "+377",
        code: "MC",
        flagEmoji: "🇲🇨",
        flagIconCircle: "assets/circle/MC.svg",
        flagIconSquare: "assets/square/MC.svg"),
    MaxCountry(
        name: "Mongolia",
        dialCode: "+976",
        code: "MN",
        flagEmoji: "🇲🇳",
        flagIconCircle: "assets/circle/MN.svg",
        flagIconSquare: "assets/square/MN.svg"),
    MaxCountry(
        name: "Montenegro",
        dialCode: "+382",
        code: "ME",
        flagEmoji: "🇲🇪",
        flagIconCircle: "assets/circle/ME.svg",
        flagIconSquare: "assets/square/ME.svg"),
    MaxCountry(
        name: "Montserrat",
        dialCode: "+1664",
        code: "MS",
        flagEmoji: "🇲🇸",
        flagIconCircle: "assets/circle/MS.svg",
        flagIconSquare: "assets/square/MS.svg"),
    MaxCountry(
        name: "Morocco",
        dialCode: "+212",
        code: "MA",
        flagEmoji: "🇲🇦",
        flagIconCircle: "assets/circle/MA.svg",
        flagIconSquare: "assets/square/MA.svg"),
    MaxCountry(
        name: "Mozambique",
        dialCode: "+258",
        code: "MZ",
        flagEmoji: "🇲🇿",
        flagIconCircle: "assets/circle/MZ.svg",
        flagIconSquare: "assets/square/MZ.svg"),
    MaxCountry(
        name: "Myanmar",
        dialCode: "+95",
        code: "MM",
        flagEmoji: "🇲🇲",
        flagIconCircle: "assets/circle/MM.svg",
        flagIconSquare: "assets/square/MM.svg"),
    MaxCountry(
        name: "Namibia",
        dialCode: "+264",
        code: "NA",
        flagEmoji: "🇳🇦",
        flagIconCircle: "assets/circle/NA.svg",
        flagIconSquare: "assets/square/NA.svg"),
    MaxCountry(
        name: "Nauru",
        dialCode: "+674",
        code: "NR",
        flagEmoji: "🇳🇷",
        flagIconCircle: "assets/circle/NR.svg",
        flagIconSquare: "assets/square/NR.svg"),
    MaxCountry(
        name: "Nepal",
        dialCode: "+977",
        code: "NP",
        flagEmoji: "🇳🇵",
        flagIconCircle: "assets/circle/NP.svg",
        flagIconSquare: "assets/square/NP.svg"),
    MaxCountry(
        name: "Netherlands",
        dialCode: "+31",
        code: "NL",
        flagEmoji: "🇳🇱",
        flagIconCircle: "assets/circle/NL.svg",
        flagIconSquare: "assets/square/NL.svg"),
    MaxCountry(
        name: "Netherlands Antilles",
        dialCode: "+599",
        code: "AN",
        flagEmoji: "🇳🇱",
        flagIconCircle: "assets/circle/AN.svg",
        flagIconSquare: "assets/square/AN.svg"),
    MaxCountry(
        name: "New Caledonia",
        dialCode: "+687",
        code: "NC",
        flagEmoji: "🇳🇨",
        flagIconCircle: "assets/circle/NC.svg",
        flagIconSquare: "assets/square/NC.svg"),
    MaxCountry(
        name: "New Zealand",
        dialCode: "+64",
        code: "NZ",
        flagEmoji: "🇳🇿",
        flagIconCircle: "assets/circle/NZ.svg",
        flagIconSquare: "assets/square/NZ.svg"),
    MaxCountry(
        name: "Nicaragua",
        dialCode: "+505",
        code: "NI",
        flagEmoji: "🇳🇮",
        flagIconCircle: "assets/circle/NI.svg",
        flagIconSquare: "assets/square/NI.svg"),
    MaxCountry(
        name: "Niger",
        dialCode: "+227",
        code: "NE",
        flagEmoji: "🇳🇪",
        flagIconCircle: "assets/circle/NE.svg",
        flagIconSquare: "assets/square/NE.svg"),
    MaxCountry(
        name: "Nigeria",
        dialCode: "+234",
        code: "NG",
        flagEmoji: "🇳🇬",
        flagIconCircle: "assets/circle/NG.svg",
        flagIconSquare: "assets/square/NG.svg"),
    MaxCountry(
        name: "Niue",
        dialCode: "+683",
        code: "NU",
        flagEmoji: "🇳🇺",
        flagIconCircle: "assets/circle/NU.svg",
        flagIconSquare: "assets/square/NU.svg"),
    MaxCountry(
        name: "Norfolk Island",
        dialCode: "+672",
        code: "NF",
        flagEmoji: "🇳🇫",
        flagIconCircle: "assets/circle/NF.svg",
        flagIconSquare: "assets/square/NF.svg"),
    MaxCountry(
        name: "Northern Mariana Islands",
        dialCode: "+1670",
        code: "MP",
        flagEmoji: "🏳",
        flagIconCircle: "assets/circle/MP.svg",
        flagIconSquare: "assets/square/MP.svg"),
    MaxCountry(
        name: "Norway",
        dialCode: "+47",
        code: "NO",
        flagEmoji: "🇳🇴",
        flagIconCircle: "assets/circle/NO.svg",
        flagIconSquare: "assets/square/NO.svg"),
    MaxCountry(
        name: "Oman",
        dialCode: "+968",
        code: "OM",
        flagEmoji: "🇴🇲",
        flagIconCircle: "assets/circle/OM.svg",
        flagIconSquare: "assets/square/OM.svg"),
    MaxCountry(
        name: "Pakistan",
        dialCode: "+92",
        code: "PK",
        flagEmoji: "🇵🇰",
        flagIconCircle: "assets/circle/PK.svg",
        flagIconSquare: "assets/square/PK.svg"),
    MaxCountry(
        name: "Palau",
        dialCode: "+680",
        code: "PW",
        flagEmoji: "🇵🇼",
        flagIconCircle: "assets/circle/PW.svg",
        flagIconSquare: "assets/square/PW.svg"),
    MaxCountry(
        name: "Palestine",
        dialCode: "+970",
        code: "PS",
        flagEmoji: "🇵🇸",
        flagIconCircle: "assets/circle/PS.svg",
        flagIconSquare: "assets/square/PS.svg"),
    MaxCountry(
        name: "Panama",
        dialCode: "+507",
        code: "PA",
        flagEmoji: "🇵🇦",
        flagIconCircle: "assets/circle/PA.svg",
        flagIconSquare: "assets/square/PA.svg"),
    MaxCountry(
        name: "Papua New Guinea",
        dialCode: "+675",
        code: "PG",
        flagEmoji: "🇵🇬",
        flagIconCircle: "assets/circle/PG.svg",
        flagIconSquare: "assets/square/PG.svg"),
    MaxCountry(
        name: "Paraguay",
        dialCode: "+595",
        code: "PY",
        flagEmoji: "🇵🇾",
        flagIconCircle: "assets/circle/PY.svg",
        flagIconSquare: "assets/square/PY.svg"),
    MaxCountry(
        name: "Peru",
        dialCode: "+51",
        code: "PE",
        flagEmoji: "🇵🇪",
        flagIconCircle: "assets/circle/PE.svg",
        flagIconSquare: "assets/square/PE.svg"),
    MaxCountry(
        name: "Philippines",
        dialCode: "+63",
        code: "PH",
        flagEmoji: "🇵🇭",
        flagIconCircle: "assets/circle/PH.svg",
        flagIconSquare: "assets/square/PH.svg"),
    MaxCountry(
        name: "Pitcairn",
        dialCode: "+872",
        code: "PN",
        flagEmoji: "🇵🇳",
        flagIconCircle: "assets/circle/PN.svg",
        flagIconSquare: "assets/square/PN.svg"),
    MaxCountry(
        name: "Poland",
        dialCode: "+48",
        code: "PL",
        flagEmoji: "🇵🇱",
        flagIconCircle: "assets/circle/PL.svg",
        flagIconSquare: "assets/square/PL.svg"),
    MaxCountry(
        name: "Portugal",
        dialCode: "+351",
        code: "PT",
        flagEmoji: "🇵🇹",
        flagIconCircle: "assets/circle/PT.svg",
        flagIconSquare: "assets/square/PT.svg"),
    MaxCountry(
        name: "Puerto Rico",
        dialCode: "+1939",
        code: "PR",
        flagEmoji: "🇵🇷",
        flagIconCircle: "assets/circle/PR.svg",
        flagIconSquare: "assets/square/PR.svg"),
    MaxCountry(
        name: "Qatar",
        dialCode: "+974",
        code: "QA",
        flagEmoji: "🇶🇦",
        flagIconCircle: "assets/circle/QA.svg",
        flagIconSquare: "assets/square/QA.svg"),
    MaxCountry(
        name: "Romania",
        dialCode: "+40",
        code: "RO",
        flagEmoji: "🇷🇴",
        flagIconCircle: "assets/circle/RO.svg",
        flagIconSquare: "assets/square/RO.svg"),
    MaxCountry(
        name: "Russia",
        dialCode: "+7",
        code: "RU",
        flagEmoji: "🇷🇺",
        flagIconCircle: "assets/circle/RU.svg",
        flagIconSquare: "assets/square/RU.svg"),
    MaxCountry(
        name: "Rwanda",
        dialCode: "+250",
        code: "RW",
        flagEmoji: "🇷🇼",
        flagIconCircle: "assets/circle/RW.svg",
        flagIconSquare: "assets/square/RW.svg"),
    MaxCountry(
        name: "Reunion",
        dialCode: "+262",
        code: "RE",
        flagEmoji: "🇷🇪",
        flagIconCircle: "assets/circle/RE.svg",
        flagIconSquare: "assets/square/RE.svg"),
    MaxCountry(
        name: "Saint Barthelemy",
        dialCode: "+590",
        code: "BL",
        flagEmoji: "🇧🇱",
        flagIconCircle: "assets/circle/BL.svg",
        flagIconSquare: "assets/square/BL.svg"),
    MaxCountry(
        name: "Saint Helena, Ascension and Tristan Da Cunha",
        dialCode: "+290",
        code: "SH",
        flagEmoji: "🇸🇭",
        flagIconCircle: "assets/circle/SH.svg",
        flagIconSquare: "assets/square/SH.svg"),
    MaxCountry(
        name: "Saint Kitts and Nevis",
        dialCode: "+1869",
        code: "KN",
        flagEmoji: "🇰🇳",
        flagIconCircle: "assets/circle/KN.svg",
        flagIconSquare: "assets/square/KN.svg"),
    MaxCountry(
        name: "Saint Lucia",
        dialCode: "+1758",
        code: "LC",
        flagEmoji: "🇱🇨",
        flagIconCircle: "assets/circle/LC.svg",
        flagIconSquare: "assets/square/LC.svg"),
    MaxCountry(
        name: "Saint Martin",
        dialCode: "+590",
        code: "MF",
        flagEmoji: "🇲🇫",
        flagIconCircle: "assets/circle/MF.svg",
        flagIconSquare: "assets/square/MF.svg"),
    MaxCountry(
        name: "Saint Pierre and Miquelon",
        dialCode: "+508",
        code: "PM",
        flagEmoji: "🇵🇲",
        flagIconCircle: "assets/circle/PM.svg",
        flagIconSquare: "assets/square/PM.svg"),
    MaxCountry(
        name: "Saint Vincent and the Grenadines",
        dialCode: "+1784",
        code: "VC",
        flagEmoji: "🇻🇨",
        flagIconCircle: "assets/circle/VC.svg",
        flagIconSquare: "assets/square/VC.svg"),
    MaxCountry(
        name: "Samoa",
        dialCode: "+685",
        code: "WS",
        flagEmoji: "🇼🇸",
        flagIconCircle: "assets/circle/WS.svg",
        flagIconSquare: "assets/square/WS.svg"),
    MaxCountry(
        name: "San Marino",
        dialCode: "+378",
        code: "SM",
        flagEmoji: "🇸🇲",
        flagIconCircle: "assets/circle/SM.svg",
        flagIconSquare: "assets/square/SM.svg"),
    MaxCountry(
        name: "Sao Tome and Principe",
        dialCode: "+239",
        code: "ST",
        flagEmoji: "🇸🇹",
        flagIconCircle: "assets/circle/ST.svg",
        flagIconSquare: "assets/square/ST.svg"),
    MaxCountry(
        name: "Saudi Arabia",
        dialCode: "+966",
        code: "SA",
        flagEmoji: "🇸🇩",
        flagIconCircle: "assets/circle/SA.svg",
        flagIconSquare: "assets/square/SA.svg"),
    MaxCountry(
        name: "Senegal",
        dialCode: "+221",
        code: "SN",
        flagEmoji: "🇸🇳",
        flagIconCircle: "assets/circle/SN.svg",
        flagIconSquare: "assets/square/SN.svg"),
    MaxCountry(
        name: "Serbia",
        dialCode: "+381",
        code: "RS",
        flagEmoji: "🇷🇸",
        flagIconCircle: "assets/circle/RS.svg",
        flagIconSquare: "assets/square/RS.svg"),
    MaxCountry(
        name: "Seychelles",
        dialCode: "+248",
        code: "SC",
        flagEmoji: "🇸🇨",
        flagIconCircle: "assets/circle/SC.svg",
        flagIconSquare: "assets/square/SC.svg"),
    MaxCountry(
        name: "Sierra Leone",
        dialCode: "+232",
        code: "SL",
        flagEmoji: "🇸🇱",
        flagIconCircle: "assets/circle/SL.svg",
        flagIconSquare: "assets/square/SL.svg"),
    MaxCountry(
        name: "Singapore",
        dialCode: "+65",
        code: "SG",
        flagEmoji: "🇸🇬",
        flagIconCircle: "assets/circle/SG.svg",
        flagIconSquare: "assets/square/SG.svg"),
    MaxCountry(
        name: "Slovakia",
        dialCode: "+421",
        code: "SK",
        flagEmoji: "🇸🇰",
        flagIconCircle: "assets/circle/SK.svg",
        flagIconSquare: "assets/square/SK.svg"),
    MaxCountry(
        name: "Slovenia",
        dialCode: "+386",
        code: "SI",
        flagEmoji: "🇸🇮",
        flagIconCircle: "assets/circle/SI.svg",
        flagIconSquare: "assets/square/SI.svg"),
    MaxCountry(
        name: "Solomon Islands",
        dialCode: "+677",
        code: "SB",
        flagEmoji: "🇸🇧",
        flagIconCircle: "assets/circle/SB.svg",
        flagIconSquare: "assets/square/SB.svg"),
    MaxCountry(
        name: "Somalia",
        dialCode: "+252",
        code: "SO",
        flagEmoji: "🇸🇴",
        flagIconCircle: "assets/circle/SO.svg",
        flagIconSquare: "assets/square/SO.svg"),
    MaxCountry(
        name: "South Africa",
        dialCode: "+27",
        code: "ZA",
        flagEmoji: "🇿🇦",
        flagIconCircle: "assets/circle/ZA.svg",
        flagIconSquare: "assets/square/ZA.svg"),
    MaxCountry(
        name: "South Sudan",
        dialCode: "+211",
        code: "SS",
        flagEmoji: "🇸🇸",
        flagIconCircle: "assets/circle/SS.svg",
        flagIconSquare: "assets/square/SS.svg"),
    MaxCountry(
        name: "South Georgia and the South Sandwich Islands",
        dialCode: "+500",
        code: "GS",
        flagEmoji: "🇬🇸",
        flagIconCircle: "assets/circle/GS.svg",
        flagIconSquare: "assets/square/GS.svg"),
    MaxCountry(
        name: "Spain",
        dialCode: "+34",
        code: "ES",
        flagEmoji: "🇪🇸",
        flagIconCircle: "assets/circle/ES.svg",
        flagIconSquare: "assets/square/ES.svg"),
    MaxCountry(
        name: "Sri Lanka",
        dialCode: "+94",
        code: "LK",
        flagEmoji: "🇱🇰",
        flagIconCircle: "assets/circle/LK.svg",
        flagIconSquare: "assets/square/LK.svg"),
    MaxCountry(
        name: "Sudan",
        dialCode: "+249",
        code: "SD",
        flagEmoji: "🇸🇩",
        flagIconCircle: "assets/circle/SD.svg",
        flagIconSquare: "assets/square/SD.svg"),
    MaxCountry(
        name: "Suriname",
        dialCode: "+597",
        code: "SR",
        flagEmoji: "🇸🇷",
        flagIconCircle: "assets/circle/SR.svg",
        flagIconSquare: "assets/square/SR.svg"),
    MaxCountry(
        name: "Svalbard and Jan Mayen",
        dialCode: "+47",
        code: "SJ",
        flagEmoji: "🇸🇯",
        flagIconCircle: "assets/circle/SJ.svg",
        flagIconSquare: "assets/square/SJ.svg"),
    MaxCountry(
        name: "Swaziland",
        dialCode: "+268",
        code: "SZ",
        flagEmoji: "🇸🇿",
        flagIconCircle: "assets/circle/SZ.svg",
        flagIconSquare: "assets/square/SZ.svg"),
    MaxCountry(
        name: "Sweden",
        dialCode: "+46",
        code: "SE",
        flagEmoji: "🇸🇪",
        flagIconCircle: "assets/circle/SE.svg",
        flagIconSquare: "assets/square/SE.svg"),
    MaxCountry(
        name: "Switzerland",
        dialCode: "+41",
        code: "CH",
        flagEmoji: "🇨🇭",
        flagIconCircle: "assets/circle/CH.svg",
        flagIconSquare: "assets/square/CH.svg"),
    MaxCountry(
        name: "Syrian Arab Republic",
        dialCode: "+963",
        code: "SY",
        flagEmoji: "🇸🇾",
        flagIconCircle: "assets/circle/SY.svg",
        flagIconSquare: "assets/square/SY.svg"),
    MaxCountry(
        name: "Taiwan",
        dialCode: "+886",
        code: "TW",
        flagEmoji: "🇹🇼",
        flagIconCircle: "assets/circle/TW.svg",
        flagIconSquare: "assets/square/TW.svg"),
    MaxCountry(
        name: "Tajikistan",
        dialCode: "+992",
        code: "TJ",
        flagEmoji: "🇹🇯",
        flagIconCircle: "assets/circle/TJ.svg",
        flagIconSquare: "assets/square/TJ.svg"),
    MaxCountry(
        name: "Tanzania, United Republic of Tanzania",
        dialCode: "+255",
        code: "TZ",
        flagEmoji: "🇹🇿",
        flagIconCircle: "assets/circle/TZ.svg",
        flagIconSquare: "assets/square/TZ.svg"),
    MaxCountry(
        name: "Thailand",
        dialCode: "+66",
        code: "TH",
        flagEmoji: "🇹🇭",
        flagIconCircle: "assets/circle/TH.svg",
        flagIconSquare: "assets/square/TH.svg"),
    MaxCountry(
        name: "Timor-Leste",
        dialCode: "+670",
        code: "TL",
        flagEmoji: "🇹🇱",
        flagIconCircle: "assets/circle/TL.svg",
        flagIconSquare: "assets/square/TL.svg"),
    MaxCountry(
        name: "Togo",
        dialCode: "+228",
        code: "TG",
        flagEmoji: "🇹🇬",
        flagIconCircle: "assets/circle/TG.svg",
        flagIconSquare: "assets/square/TG.svg"),
    MaxCountry(
        name: "Tokelau",
        dialCode: "+690",
        code: "TK",
        flagEmoji: "🇹🇰",
        flagIconCircle: "assets/circle/TK.svg",
        flagIconSquare: "assets/square/TK.svg"),
    MaxCountry(
        name: "Tonga",
        dialCode: "+676",
        code: "TO",
        flagEmoji: "🇹🇴",
        flagIconCircle: "assets/circle/TO.svg",
        flagIconSquare: "assets/square/TO.svg"),
    MaxCountry(
        name: "Trinidad and Tobago",
        dialCode: "+1868",
        code: "TT",
        flagEmoji: "🇹🇹",
        flagIconCircle: "assets/circle/TT.svg",
        flagIconSquare: "assets/square/TT.svg"),
    MaxCountry(
        name: "Tunisia",
        dialCode: "+216",
        code: "TN",
        flagEmoji: "🇹🇳",
        flagIconCircle: "assets/circle/TN.svg",
        flagIconSquare: "assets/square/TN.svg"),
    MaxCountry(
        name: "Turkey",
        dialCode: "+90",
        code: "TR",
        flagEmoji: "🇹🇷",
        flagIconCircle: "assets/circle/TR.svg",
        flagIconSquare: "assets/square/TR.svg"),
    MaxCountry(
        name: "Turkmenistan",
        dialCode: "+993",
        code: "TM",
        flagEmoji: "🇹🇲",
        flagIconCircle: "assets/circle/TM.svg",
        flagIconSquare: "assets/square/TM.svg"),
    MaxCountry(
        name: "Turks and Caicos Islands",
        dialCode: "+1649",
        code: "TC",
        flagEmoji: "🇹🇨",
        flagIconCircle: "assets/circle/TC.svg",
        flagIconSquare: "assets/square/TC.svg"),
    MaxCountry(
        name: "Tuvalu",
        dialCode: "+688",
        code: "TV",
        flagEmoji: "🇹🇻",
        flagIconCircle: "assets/circle/TV.svg",
        flagIconSquare: "assets/square/TV.svg"),
    MaxCountry(
        name: "Uganda",
        dialCode: "+256",
        code: "UG",
        flagEmoji: "🇺🇬",
        flagIconCircle: "assets/circle/UG.svg",
        flagIconSquare: "assets/square/UG.svg"),
    MaxCountry(
        name: "Ukraine",
        dialCode: "+380",
        code: "UA",
        flagEmoji: "🇺🇦",
        flagIconCircle: "assets/circle/UA.svg",
        flagIconSquare: "assets/square/UA.svg"),
    MaxCountry(
        name: "United Arab Emirates",
        dialCode: "+971",
        code: "AE",
        flagEmoji: "🇦🇪",
        flagIconCircle: "assets/circle/AE.svg",
        flagIconSquare: "assets/square/AE.svg"),
    MaxCountry(
        name: "United Kingdom",
        dialCode: "+44",
        code: "GB",
        flagEmoji: "🇬🇧",
        flagIconCircle: "assets/circle/GB.svg",
        flagIconSquare: "assets/square/GB.svg"),
    MaxCountry(
        name: "United States",
        dialCode: "+1",
        code: "US",
        flagEmoji: "🇺🇸",
        flagIconCircle: "assets/circle/US.svg",
        flagIconSquare: "assets/square/US.svg"),
    MaxCountry(
        name: "Uruguay",
        dialCode: "+598",
        code: "UY",
        flagEmoji: "🇺🇾",
        flagIconCircle: "assets/circle/UY.svg",
        flagIconSquare: "assets/square/UY.svg"),
    MaxCountry(
        name: "Uzbekistan",
        dialCode: "+998",
        code: "UZ",
        flagEmoji: "🇺🇿",
        flagIconCircle: "assets/circle/UZ.svg",
        flagIconSquare: "assets/square/UZ.svg"),
    MaxCountry(
        name: "Vanuatu",
        dialCode: "+678",
        code: "VU",
        flagEmoji: "🇻🇺",
        flagIconCircle: "assets/circle/VU.svg",
        flagIconSquare: "assets/square/VU.svg"),
    MaxCountry(
        name: "Venezuela, Bolivarian Republic of Venezuela",
        dialCode: "+58",
        code: "VE",
        flagEmoji: "🇻🇪",
        flagIconCircle: "assets/circle/VE.svg",
        flagIconSquare: "assets/square/VE.svg"),
    MaxCountry(
        name: "Vietnam",
        dialCode: "+84",
        code: "VN",
        flagEmoji: "🇻🇳",
        flagIconCircle: "assets/circle/VN.svg",
        flagIconSquare: "assets/square/VN.svg"),
    MaxCountry(
        name: "Virgin Islands, British",
        dialCode: "+1284",
        code: "VG",
        flagEmoji: "🇻🇬",
        flagIconCircle: "assets/circle/VG.svg",
        flagIconSquare: "assets/square/VG.svg"),
    MaxCountry(
        name: "Virgin Islands, U.S.",
        dialCode: "+1340",
        code: "VI",
        flagEmoji: "🇻🇮",
        flagIconCircle: "assets/circle/VI.svg",
        flagIconSquare: "assets/square/VI.svg"),
    MaxCountry(
        name: "Wallis and Futuna",
        dialCode: "+681",
        code: "WF",
        flagEmoji: "🇼🇫",
        flagIconCircle: "assets/circle/WF.svg",
        flagIconSquare: "assets/square/WF.svg"),
    MaxCountry(
        name: "Yemen",
        dialCode: "+967",
        code: "YE",
        flagEmoji: "🇾🇪",
        flagIconCircle: "assets/circle/YE.svg",
        flagIconSquare: "assets/square/YE.svg"),
    MaxCountry(
        name: "Zambia",
        dialCode: "+260",
        code: "ZM",
        flagEmoji: "🇿🇲",
        flagIconCircle: "assets/circle/ZM.svg",
        flagIconSquare: "assets/square/ZM.svg"),
    MaxCountry(
        name: "Zimbabwe",
        dialCode: "+263",
        code: "ZW",
        flagEmoji: "🇿🇼",
        flagIconCircle: "assets/circle/ZW.svg",
        flagIconSquare: "assets/square/ZW.svg"),
  ];
}
